### PR TITLE
move node-webkit to additionalTargets + export additionalTargets

### PR DESCRIPTION
**Pull request by ralphtheninja**
Merging this will affect https://github.com/lgeiger/node-abi/pull/34

### CODE REVIEW

**Comment by ralphtheninja** [comment]
@saboya So this PR is blocking https://github.com/lgeiger/node-abi/pull/34, which is blocking https://github.com/prebuild/prebuild/pull/203 ;)

**Comment by saboya** [comment]
I was waiting on a definition regarding the `allTargets` / `additionalTargets` issue before making any changes.

Anyway, adding `additionalTargets` to `allTargets` lead to the same issue? Anyone that uses `allTargets` would be affected by the change.

I'm not partcularly for or against any of the proposed solutions. If you think this is the best way to it and it's according to `node-abi`ś design intent, I'll just merge it.

**Comment by ralphtheninja** [comment]
@saboya The issue was not about `allTargets` but `supportedTargets` which is what prebuild uses here https://github.com/prebuild/prebuild/blob/master/rc.js#L2 , `allTargets` are really _all_ targets, including deprecated versions.

**Comment by ralphtheninja** [comment]
You can just merge it to see what everyone thinks of the PR. It's still your branch at the moment :)

**Pull request merged**
